### ISSUE TITLE
Milestone 2 code feedback

### ISSUE THREAD

**Issue by andytai7** [UBC-MDS/pythcat#63]
Great Job, Python code was clear and ran without bugs. In addition, i see clearly who reviewed who's code on the Repos in pull requests.  
Just a note on R, i know that we don't have poetry running right now, but i am installing packages, should include install.packages("testthat"). Tests all ran perfectly with Python, but R needs some work. Repwithna and topcorr worked.

**Comment by HanyingZhang** [comment]
Thanks a lot for the feedback Andy! But we might need a little more explanation to address this feedback.  
Where should we add `install.packages("testthat")` to? Is it in readme?   
And can you tell which part is not working for you? It seems to us that all tests are passed.  
Thank you very much if you could clarify these.

**Comment by doraqmon** [comment]
Hi, @andytai7 we have tested all our R test functions on different machines. It does not seem to have any problem. Also, our R-CMD is passed. I think our functions are good. We will close this issue.
Thank you.

**Comment by doraqmon** [comment]
for testthat package, it is already under our DESCRIPTION section. R does not using poetry, it use devtools. So I think we are fine.

<img width="718" alt="image" src="https://user-images.githubusercontent.com/49354741/76689879-ad79f580-65f7-11ea-8db7-fc2cf0f857e8.png">
